version: "3.9"

services:
  speedtrap-api:
    image: kxpic/api-handler
    env_file:
      - ./app/.env
    networks:
      - bbb
    volumes:
      - ./tickets:/opt

  speedtrap-camera:
    image: kxpic/camera
    env_file:
      - ./camera/.env
    networks:
      - bbb
    volumes:
      - ./tickets:/opt
    devices:
      - /dev/video0:/dev/video0
    privileged: true

networks:
  bbb:
    driver: bridge